name: test
on:
  push:
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: ls -lah
      - run: renovate-config-validator --strict *.json5
